### ISSUE TITLE
LoadError: cannot load such file -- mina/whenever

### ISSUE THREAD

**Issue by floydj** [mina-deploy/mina-whenever#2]
Rails 5 app, upgrading to Mina 1.0. Added the mina-whenever gem to my gemfile and ran `bundle install`, everything seemed to go ok.

In my `config/deploy.rb` file:

`require 'mina/whenever'`

`mina deploy` gives me the `LoadError: cannot load such file -- mina/whenever` message.

How do I resolve this?

**Comment by myserg** [comment]
Just use require 'mina/whenever/tasks'

**Comment by alxx** [comment]
@myserg, that did not work for me.

```
$ gem list whenever
*** LOCAL GEMS ***
whenever (0.9.7)
```

and then

```
$ mina server:console -f config/deploy_production.rb
mina aborted!
LoadError: cannot load such file -- mina/whenever/tasks
```

Do you have any suggestions?

**Comment by myserg** [comment]
'mina-whenever' gem should be installed

$ gem list whenever

**\* LOCAL GEMS ***

mina-whenever (1.0.0)
whenever (0.9.4)

**Comment by alxx** [comment]
That wasn't a requirement before, but it works now. Thanks.

**Comment by alxx** [comment]
It has to be installed like this:

```
gem 'mina-whenever', require: false
```

**Comment by alvesoaj** [comment]
The problem still exists! None off suggestions solved for me.

**Comment by minimul** [comment]
Make sure you are on '0.3.x' e.g.

```

group :development do
    gem 'mina', '~> 0.3.0'
end

```

Then make sure to run the bundled version

```
bundle exec mina deploy
```

**Comment by tejasukal** [comment]
I'm facing "loaderror: cannot load such file -- mina/puma" error while deploying my code what could be possibly wrong with it?
